### ISSUE TITLE
Everyone can spam on their own repos, #StopShitoberfest

### ISSUE THREAD

**Issue by silentWatcher3** [abhisri459/hightech#12]
![image](https://user-images.githubusercontent.com/71167111/135607457-40f6e46d-165f-4fef-b784-9126c477c2c5.png)

**Comment by silentWatcher3** [comment]
https://twitter.com/shitoberfest/status/1443711969626767360

**Comment by abhisri459** [comment]
> https://twitter.com/shitoberfest/status/1443711969626767360

That was a mistake sir, I sincerely regret it and promise to never repeat it.
